### ISSUE TITLE
build with GPU failed on Ubuntu 18.10, CUDA 9.0

### ISSUE THREAD

**Issue by we-taper** [qulacs/qulacs#116]
Hi there. Very nice to see this fantastic project. However, when I tried to build the GPU version, it failed with ` unsupported GNU version! gcc versions later than 6 are not supported!`. I tried building without GPU and it worked.

I am using the latest version of qulacs (git cloned this repository). Please find the build output attached:
[build_output_gpu_qulacs.txt](https://github.com/qulacs/qulacs/files/2945596/build_output_gpu_qulacs.txt)

**Comment by corryvrequan** [comment]
Thank you for reporting bugs!

This error occurs since CUDA 9.0 does not support gcc>=6. 
We will try to regenerate errors and report how to fix it after that.

**Comment by TenninYan** [comment]
@we-taper Can you upgrade CUDA to 9.2 or above?
That should work with gcc7.
