### ISSUE TITLE
MultiQubitDepolarizingNoise を追加で実装

### ISSUE THREAD

**Issue by yamamoto-takahiro** [qulacs/qulacs#146]
## 修正内容
[`gate_factory.cpp`](https://github.com/qulacs/qulacs/blob/d81f3884d4af8550718b9dc5b84fc7d68416ebef/src/cppsim/gate_factory.cpp)
に`MultiQubitDepolarizingNoise` を追加する (2-qubit gate までで十分)

Python 版 (Qulacs+) の実装:
https://github.com/QunaSys/plus/pull/170/files#diff-25db80919a1df84b5035e84899e435deR4

**Comment by corryvrequan** [comment]
機能を追加したものをマージしたのでcloseします。何か問題があればissueを立ててもらえれば幸いです
