### ISSUE TITLE
build failure on Ubuntu 18.04 (CPU only)

### ISSUE THREAD

**Issue by miyo** [qulacs/qulacs#151]
Build failure occurred on my environment, Ubuntu 18.04 with gcc 7.4.0 and cmake 3.10.2.
```
$ git clone https://github.com/qulacs/qulacs.git
$ python3 setup.py install --user
[ 54%] Building CXX object src/cppsim/CMakeFiles/cppsim_static.dir/circuit.cpp.o
In file included from /home/miyo/src/qulacs/src/cppsim/circuit_optimizer.hpp:4:0,
                 from /home/miyo/src/qulacs/src/cppsim/circuit_optimizer.cpp:4:
/home/miyo/src/qulacs/src/cppsim/type.hpp:5:10: fatal error: csim/type.h: No such file or directory
 #include <csim/type.h>
          ^~~~~~~~~~~~~
compilation terminated.
src/cppsim/CMakeFiles/cppsim_static.dir/build.make:86: recipe for target 
...
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'python', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2.
```
It seems that there does not exist include files in expected directories. After the following quick hacks, the build is succeeded.
```
 mkdir include/{csim,cppsim,vqcsim}
 ln -s `pwd`/src/csim/*.{h,hpp} `pwd`/include/csim
 ln -s `pwd`/src/cppsim/*.hpp `pwd`/include/cppsim
 ln -s `pwd`/src/vqcsim/*.hpp `pwd`/include/vqcsim
```
Could you tell me your correct build way?

**Comment by corryvrequan** [comment]
Thanks for reporting problems. I've tested it in a similar situation, but I could successfully build couldn't regenerate the above errors.
Thus, I wanna ask more detail about this error if possible. 

In a correct senario, cmake will copy all the (*.hpp and *.h files) in (csim,cppsim,vqcsim) to 
a folder "./qulacs/include/ folder". If you don't have "include" folder or don't have any header files or folders in "include" folder, there is a something wrong in the beginning of cmake build.

Can I ask followings for solving the problem more?
1. Can I ask a detailed situation about "include" folder?
2. Is there any warning/error message which seems to be related to this issue at the beginning of cmake build?
3. Can you try "./script/build_gcc.sh" command from qulacs folder? This will build qulacs without python setuptools.

Note that I used the following environment.
(Ubuntu 18.04.02, gcc 7.4.0, cmake 3.10.2) in virtual box running on windows10.
I've used current master branch of github.com/qulacs/qulacs, and installed qulacs with the same commands. I installed it with python 3.7.4 with pyenv 1.2.13.




```

```

**Comment by miyo** [comment]
Thank you for your quick response and testing the behavior. I tried the installation process again, and regenerated that again.  The attached `typescript.1.txt` is the log file.
[typescript.1.txt](https://github.com/qulacs/qulacs/files/3455140/typescript.1.txt)
I tried the process in $HOME/src.
Meanwhile I tried same instration process in the other directory($HOME/tmp), it worked well.
[typescript.2.txt](https://github.com/qulacs/qulacs/files/3455158/typescript.2.txt)
I don't know the reason why the installation process is failed in $HOME/src on my environment, but it might depends on my environment.

**Comment by miyo** [comment]
I think that the following in CMakeList.txt does not work when the working directory contains `src`.
```
##### configure include files #####
file(GLOB_RECURSE header_files ${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h)
foreach(path IN LISTS header_files)
        string(REPLACE /src/ /include/ path_dst ${path})
        configure_file(${path} ${path_dst} COPYONLY)
endforeach()
```
When I modified the above into the following, it works well.
```
##### configure include files #####
file(GLOB_RECURSE header_files ${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h)
foreach(path IN LISTS header_files)
        string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR}/src/ ${CMAKE_CURRENT_SOURCE_DIR}/include/ path_dst ${path})
        configure_file(${path} ${path_dst} COPYONLY)
endforeach()
```
The difference is the following.
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0bdf430..ea145a2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -39,7 +39,7 @@ message(STATUS "USE_PYTHON = ${USE_PYTHON}")
 ##### configure include files #####
 file(GLOB_RECURSE header_files ${CMAKE_CURRENT_SOURCE_DIR}/src/*.hpp  ${CMAKE_CURRENT_SOURCE_DIR}/src/*.h)
 foreach(path IN LISTS header_files)
-       string(REPLACE /src/ /include/ path_dst ${path})
+       string(REPLACE ${CMAKE_CURRENT_SOURCE_DIR}/src/ ${CMAKE_CURRENT_SOURCE_DIR}/include/ path_dst ${path})
        configure_file(${path} ${path_dst} COPYONLY)
 endforeach()
```

**Comment by corryvrequan** [comment]
I see. I think you are right.
We are sorry if our cmake scripts made garbage folders in your env, and thanks for making update patches. 
There should be the same problem when we install qulacs in any way when path of temporal build folder contains "/src/". I will immediately made PR about that.

**Comment by miyo** [comment]
I hope you make PR about this.

**Comment by corryvrequan** [comment]
Thanks, so I will make PR immediately.
