### ISSUE TITLE
parametric multi pauli gateのtarget指定

### ISSUE THREAD

**Issue by kenjikun** [qulacs/qulacs#158]
`add_parametric_multi_Pauli_rotation_gate`
において，targetを[0,0]等，同じqubitを指定すると現在はサポートされていない動作となっていると思いますが，例外をthrowしてほしいです．
量子回路を乱数を用いて生成する際などに同じqubitを指定した場合に予期せない結果になるのを避けたいです

**Comment by corryvrequan** [comment]
提案ありがとうございます。
PR #159 で以下のように処置しました。

- C++ qulacs
従来はCNOT(0,0)などを生成し量子状態を更新しても、作用する量子状態のサイズが十分大きければ高い確率でnan/inf/segfaultを生じずに普通に計算が通ってしまった。
更新後はsegfaultを起こさず誤った計算をするゲート生成を検出し、ゲートを生成せずnullptrを返す。同時にstderrにエラーメッセージを表示する。そのまま無視して計算するとnullptrを参照しsegfaultで計算が落ちる。最適化に不安が残るためコアライブラリには例外処理を入れたくないためstderrにメッセージを表示しnullptrを返す形で対処。

- python qulacs
従来はC++と同じ。
更新後はC++の回数コールをフックしてゲート生成に対しC++より多くのチェックを入れ、不正な引数に対してstd::invalid_argumentをthrowする。(invalid argumentはpybind11がValueErrorに変換する。)

pythonに関しては以前類似したバグの相談があった以下のケースに対しても例外を送出します。

- m-qubit DenseMatrix gateを2^m次元以外の行列で生成しようとしたとき
- m-qubit Pauli (rotation) gateをm個以外のパウリ配列で生成しようとしたとき
