### ISSUE TITLE
Build error on Mac

### ISSUE THREAD

**Issue by rtmatphys** [qulacs/qulacs#162]
Hi. I had a build error when I tried to install the python interface on my Mac laptop (Mojave 10.14.1) with python 2.7.10, gcc/g++ 9.2.0, and cmake 3.15.3. 

The error message reads as follows;

[ 97%] Building CXX object python/CMakeFiles/qulacs.dir/cppsim_wrapper.cpp.o
In file included from /Users/rt/qulacs/build/temp.macosx-10.14-intel-2.7/_deps/pybind11_fetch-src/include/pybind11/pytypes.h:12,
                 from /Users/rt/qulacs/build/temp.macosx-10.14-intel-2.7/_deps/pybind11_fetch-src/include/pybind11/cast.h:13,
                 from /Users/rt/qulacs/build/temp.macosx-10.14-intel-2.7/_deps/pybind11_fetch-src/include/pybind11/attr.h:13,
                 from /Users/rt/qulacs/build/temp.macosx-10.14-intel-2.7/_deps/pybind11_fetch-src/include/pybind11/pybind11.h:43,
                 from /Users/rt/qulacs/python/cppsim_wrapper.cpp:2:
/Users/rt/qulacs/build/temp.macosx-10.14-intel-2.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h: In instantiation of 'struct pybind11::overload_cast<const QuantumStateCpu*, const QuantumStateCpu*>':
/Users/rt/qulacs/python/cppsim_wrapper.cpp:220:114:   required from here
/Users/rt/qulacs/build/temp.macosx-10.14-intel-2.7/_deps/pybind11_fetch-src/include/pybind11/detail/common.h:755:65: error: static assertion failed: pybind11::overload_cast<...> requires compiling in C++14 mode

I would be very glad if I could get some suggestion.
Best regards.

**Comment by rtmatphys** [comment]
@TenninYan Thank you for the quick response.
I tried an installation with Python 3.7.4, and yet I still got the same error...

**Comment by corryvrequan** [comment]
Thanks for reporting error, @rtmatphys.
This error probably caused by incompatibility between our cmake script and the latest pybind11 or gcc. In the latest environment, build with pybind11 requires C++14 features but our cmake only gives C++11 flag to gcc. Since similar errors are reported by other environment, we plan to resolve this problem soon by improving cmake script.

Note that if you try local installation, replace "-std=gnu++11" in CMakeLists.txt at ./qulacs/ to "-std=gnu++14" may fix this problems.

**Comment by rtmatphys** [comment]
@corryvrequan Thank you for your response. I appreciate you planning to update the cmake script. I will wait for that.

Note: 
I attempted installation after replacing "-std=gnu++11" for "-std=gnu++14" in CMakeLists.txt, but I still got an error, which follows

>  [ 61%] Building CXX object src/cppsim/CMakeFiles/cppsim_static.dir/gate_matrix.cpp.o
> cc1plus: warning: '-Werror=' argument '-Werror=missing-prototypes' is not valid for C++
> cc1plus: warning: '-Werror=' argument '-Werror=implicit-function-declaration' is not valid for C++
> cc1plus: warning: '-Werror=' argument '-Werror=incompatible-pointer-types' is not valid for C++
> In file included from /Users/rt/qulacs/src/cppsim/gate_factory.cpp:12:
> /Users/rt/qulacs/src/cppsim/gate_named_one.hpp: In constructor 'ClsYGate::ClsYGate(UINT)':
> /Users/rt/qulacs/src/cppsim/gate_named_one.hpp:88:37: error: unable to find numeric literal operator 'operator""i'
>    88 |         this->_matrix_element << 0,-1.i,1.i,0;

**Comment by corryvrequan** [comment]
@rtmatphys 
Sorry for late reply. I regenerated the same error. Though errors by pybind11 is solved by replacing gnu++11 to gnu++14, other errors related to imaginary value literals happen. Though it is very temporal fix, the following change will resolve this error.

1. Replace "-std=gnu++11" for "-std=gnu++14" as you did.

2. Open a file at ./src/cppsim/type.hpp, and please add a line 
```
using namespace std::complex_literals;
```
to line 15. The resultant file around L15 seems
```
#include <complex>
#include <Eigen/Core>
#include <Eigen/Sparse>
typedef std::complex<double> CPPCTYPE;
typedef Eigen::VectorXcd ComplexVector;
```

3. Rebuild qulacs from source. This can be done with command
```
> ./script/build_gcc.sh
```
or if you want to install qulacs as python libs
```
> python setup.py install
```

Please let me know if the above does not work. Thanks.

**Comment by rtmatphys** [comment]
@corryvrequan After I made the above adjustments, I got to successfully complete the installation. I appreciate your suggestion!! Thank you.
