### ISSUE TITLE
Multi GPU support

### ISSUE THREAD

**Issue by ycchen1989** [qulacs/qulacs#210]
Is it able to use multi GPU on a single machine or across multiple machines?

**Comment by corryvrequan** [comment]
One possible purpose of using multi-GPU is to speed-up sampling task like simulation of quantum circuits under general errors by independent parallel simulations on each GPU. If you expect this, answer is yes.
When your machine has multiple GPUs, qulacs can choose a GPU to allocate quantum state. For example, when you have 3 GPUs, you can allocate quantum state on 0-th GPU with the following codes.
```
from qulacs import QuantumStateGpu
n_qubit = 10
gpu_id = 0
state = QuantumStateGpu(n_qubit, gpu_id)
```

On the other hand, if you want to use multi-GPU machine for allocating a large quantum state which requires larger memory than single typical GPU (about 16GB or 32GB) by utilizing distributed GPU computing. Unfortunately, we have not implement this feature.

**Comment by ycchen1989** [comment]
Thanks for the reply.
I am interested in developing large scale variational quantum circuits machine learning projects. That is, it may need to do hundreds of thousands of quantum circuit evaluation. I think it is possible to implement this with your suggestion.
