### ISSUE TITLE
CItation 

### ISSUE THREAD

**Issue by ycchen1989** [qulacs/qulacs#212]
Hello,
Thanks for this awesome simulation package. I used it in my research, and I just want to cite this work in my paper. Is there a official citation format for this package?

Thanks,

**Comment by TenninYan** [comment]
Thank you for using Qulacs! 
Hope you enjoyed the speed of it.

We are writing a paper of Qulacs now.
Meanwhile, please cite Github URL:
https://github.com/qulacs/qulacs

in bibtex style: 
@misc{Qulacs,
  title =     {{Qulacs}},
  year =      {2018},
  eprint = "https://github.com/qulacs/qulacs"
}
