### ISSUE TITLE
Set a seed value for shot based simulations

### ISSUE THREAD

**Issue by irfankhan10** [qulacs/qulacs#218]
Hi, I would like to set a seed value when sampling an observable N times using the python interface to Qulacs. Please can somebody kindly assist with this?

**Comment by corryvrequan** [comment]
Hi @irfankhan10, thanks for being interested in qulacs.
Unfortunately, qulacs does not have a feature to use a given seed in sampling bitstrings from quantum state. I can understand there are demands to sample bitstrings with given seeds, so this will be implemented in the future.

For now, if you want to manage random seed for regeneration, I recommend sampling through NumPy.
For example, I guess the following steps would work.

1. Simulate quantum circuit and obtain the final state.
2. Change measurement basis according to each Pauli term of observable.
3. Obtain state vector with "get_vector" function of QuantumState class.
4. Sampling N-times with np.random.Generator.choice function with weight np.abs(state_vector)**2.
5. Repeat step 3 and 4 for every Pauli term and sum them.

About "get_vector" function of qulacs, official examples may helpful.
http://docs.qulacs.org/en/latest/intro/4.1_python_tutorial.html#

For the use of numpy's choice function with seed, please see the official document.
https://numpy.org/doc/stable/reference/random/index.html
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html

**Comment by corryvrequan** [comment]
Hi @irfankhan10, thanks for being interested in qulacs.
Unfortunately, qulacs does not have a feature to use a given seed in sampling bitstrings from quantum state now. I can understand there are demands to sample bitstrings with given seeds, so this will be implemented in the future.

For now, if you want to manage random seed for regeneration, I recommend sampling through NumPy.
For example, I guess the following steps would work.

1. Simulate quantum circuit and obtain the final state.
2. Change measurement basis according to each Pauli term of observable.
3. Obtain state vector with "get_vector" function of QuantumState class.
4. Sampling N-times with np.random.Generator.choice function with weight np.abs(state_vector)**2.
5. Repeat step 3 and 4 for every Pauli term and sum them.

About "get_vector" function of qulacs, official examples may helpful.
http://docs.qulacs.org/en/latest/intro/4.1_python_tutorial.html#

For the use of numpy's choice function with seed, please see the official document.
https://numpy.org/doc/stable/reference/random/index.html
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html

**Comment by iwilliamscq** [comment]
Has this been fixed now?

**Comment by forest1040** [comment]
> Has this been fixed now?

Unfortunately, no.
we add sampling method parameter random_seed.
but it is used by only MPI.
https://github.com/qulacs/qulacs/blob/main/src/cppsim/state.hpp#L935

**Comment by ikanago** [comment]
@irfankhan10 @iwilliamscq 
There is an API to do sampling with a random seed in Python binding. Please check and notify if you still have a problem
https://github.com/qulacs/qulacs/blob/286862245160a52e7295038d76ea17d77b5d53bc/pysrc/qulacs/__init__.pyi#L224-L228
