### ISSUE TITLE
Issue installing with python on cluster

### ISSUE THREAD

**Issue by mlxd** [qulacs/qulacs#227]
Hi, I have been attempting to build and install qulacs into a python env on our HPC system. Building using the CMake builder works fine (we use `module load gcc` to pull in different gcc versions). 

However, the Python CMake builder (function https://github.com/qulacs/qulacs/blob/master/setup.py#L21) appends version strings to the end of gcc (`gcc-8` and `g++-8` in this instance, https://github.com/qulacs/qulacs/blob/master/setup.py#L61 and https://github.com/qulacs/qulacs/blob/master/setup.py#L68), which ensures the build fails as it is not the practice to label the binaries as such on HPC systems. My current workaround for this is to create a local symlink with the expected binary name in the build directory, add it to the path and proceed. Though, I feel this is not a good solution to ensure a solid build procedure.

Is this append necessary, as the appropriate version should already be found by the CMake build system? Or if so, is there a recommended patch that could avoid the above symlink workaround.

Thanks in advance for your help.

**Comment by corryvrequan** [comment]
Hi, @mlxd. Thanks for your comments on our build systems and sorry for the inconvenience in the installation.

As you mentioned, the current CMake script around gcc-versioning may unnecessarily append version string. In particular, when gcc_version >= LooseVersion('7.0.0') is satisfied, I guess we don't need version string. We haven't supposed this append conflicts with gcc version management systems. 
We would like to support build systems as many as possible, so we would like to rewrite these lines in the near future update.

For a quick-fix, I think putting symlink is one of the simplest solutions.
If you don't want to create symlink, another possible patch is the following process, though this requires several processes and inconvenience is not so improved.
1. Clone qulacs repository
2. Edit setup.py: replacing L58-L71 to the following two lines
```
cmake_args += ['-DCMAKE_C_COMPILER=gcc']
cmake_args += ['-DCMAKE_CXX_COMPILER=g++']
```
3. Install qulacs with <code>python setup.py install</code>.

**Comment by mlxd** [comment]
Hi @corryvrequan thanks for the prompt response. I can can continue using the symlink build process for the moment, though may see if a sed-enabled replace with the above lines fits my current workflow. Thanks again for the help, and suggestions.

**Comment by kwkbtr** [comment]
This PR #216 may be a solution?

**Comment by mlxd** [comment]
That worked perfectly. Thanks @kwkbtr
