### ISSUE TITLE
S, Sdag, T, Tdag gates commute properties

### ISSUE THREAD

**Issue by akpc** [qulacs/qulacs#231]
Currently it seem that S, Sdag, T, Tdag gates' `TargetQubitInfo` was set with `TargetQubitInfo(target_qubit_index, 0)`

Proposed changes:
```
        this->_target_qubit_list.push_back(TargetQubitInfo(target_qubit_index, FLAG_Z_COMMUTE));
```

**Comment by corryvrequan** [comment]
This bug is fixed by PR #232 .Thanks @akpc !
