### ISSUE TITLE
Qulacs on MacOS 10.14 raises errors

### ISSUE THREAD

**Issue by eileen-kuehn** [qulacs/qulacs#280]
The installation of Qulacs via `pip install qulacs` does not work for MacOS 10.14.x.

```
Collecting qulacs
  Downloading Qulacs-0.2.0-cp37-cp37m-macosx_10_9_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 3.0 MB/s 
Installing collected packages: qulacs
Successfully installed qulacs-0.2.0
```

The package seems to be built for MacOS 10.15, see stack trace below:

```
Traceback (most recent call last):
  File "~/development/main.py", line 319, in <module>
    result = train(train_params, train_data=train_data, train_target=train_target)
  File "~/development/main.py", line 96, in train
    dev = get_device(train_params["sim_local"], wires=wires)
  File "~/development/main.py", line 23, in get_device
    dev = qml.device("qulacs.simulator", wires=wires, analytic=analytic)
  File "~/development/venvs/quantum3.7/lib/python3.7/site-packages/pennylane/__init__.py", line 214, in device
    plugin_device_class = plugin_devices[name].load()
  File "~/development/venvs/quantum3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "~/development/venvs/quantum3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "~/development/venvs/quantum3.7/lib/python3.7/site-packages/pennylane_qulacs/qulacs_device.py", line 27, in <module>
    import qulacs.gate as gate
ImportError: dlopen(~/development/venvs/quantum3.7/lib/python3.7/site-packages/qulacs.cpython-37m-darwin.so, 2): Symbol not found: _aligned_alloc
  Referenced from: ~/development/venvs/quantum3.7/lib/python3.7/site-packages/qulacs.dylibs/libstdc++.6.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in ~/development/venvs/quantum3.7/lib/python3.7/site-packages/qulacs.dylibs/libstdc++.6.dylib
```

**Comment by corryvrequan** [comment]
Hi @eileen-kuehn 

Can you try with the following commands?
```
pip install git+https://github.com/qulacs/qulacs.git@dev
```
If errors like "gcc/g++ does not found" appear, please install gcc/g++ to your Mac.
If other errors are shown, please let me know.

If you use Mac with "Apple M1 CPU", this CPU does not support several CPU operations used in qulacs.
I guess `_aligned_alloc` in your error message is one of such operations (so sorry if my guess is wrong.)
In this case, we need to compile the source code of qulacs for installation.

**Comment by eileen-kuehn** [comment]
@corryvrequan, yes, the building works like a charm :)

You may want to remove the MacOS wheels if they do not work anyway. `pip` should be able to automatically build your package from source then.

**Comment by corryvrequan** [comment]
@eileen-kuehn 
I'm happy to hear that, and thanks for the suggestion!

Actually, now I'm not sure how we should manage pypi package for MacOS...
I believe the current package works for most of Mac, except for the latest model. 
If I set build-from-source as default, it requires recent gcc/g++ are installed and takes few minutes for compilation.  So, I will add notes on readme to use source build if simpe pip does not work, check how other python libraries manage it, and decide whether we should upload binary to pypi or not.
