### ISSUE TITLE
Memory leak from create_quantum_operator_from_openfermion_text

### ISSUE THREAD

**Issue by JamesB-1qbit** [qulacs/qulacs#303]
Tested in both Linux and MacOS. 
The code 
```python3
import qulacs
from openfermion import QubitOperator


qu_op = QubitOperator("X0 X1 X2 X3 X4 X5", 1.)
qu_op += QubitOperator("X0 Y1 Z2 X3 Y4 X5", 1.)
qu_op += QubitOperator("Z0 Y1 X2 Z3 Y4 X5", 1.)
for i in range(500000):
    op = qulacs.quantum_operator.create_quantum_operator_from_openfermion_text(qu_op.__repr__())
```

with `memory_profiler`, `mprof run python3 op_from_of_leak.py` results in `mprof plot`

![Figure_1](https://user-images.githubusercontent.com/84878946/152826040-c913919a-6853-47f6-9ccf-05b1a6f9494f.png)

**Comment by kwkbtr** [comment]
A new version v0.3.1 with the bug fix is released.
https://github.com/qulacs/qulacs/releases/tag/v0.3.1
