### ISSUE TITLE
Python 3.10 support?

### ISSUE THREAD

**Issue by isobelhooper** [qulacs/qulacs#310]
I noticed that commit https://github.com/qulacs/qulacs/commit/87e2945ad70c4e556af30cbc70c8a3bf270d72d4 explicitly skips building Python 3.10 wheels with cibuildwheel. Would it be possible to re-enable building those wheels, now that Python 3.10 has been out for about six months?

I've tried building Qulacs against Python 3.10.4 from source on Ubuntu 20.04 and it successfully ran and passed both the C++ and Python tests without any changes to Qulacs itself, so it looks like it should be feasible.

(If need be, I could try building Qulacs for Python 3.10 from source for the project I'd like to use it for, but having wheels for 3.10 would be excellent.)

**Comment by kwkbtr** [comment]
A new version v0.3.1 is just released and wheels for Python 3.10 are uploaded except for Windows.
https://pypi.org/project/Qulacs/0.3.1/#files

**Comment by isobelhooper** [comment]
Excellent, thank you very much! The Linux and MacOS wheels are the ones I was hoping for, so I'm happy to close this issue as fixed.
