### ISSUE TITLE
The state vectors results do not agree with qiskit or QuEST results

### ISSUE THREAD

**Issue by EddyTheCo** [qulacs/qulacs#311]
Hi I would like to use this library, I have setup everything but found that the the resulting state vector after applying certain gates do not agrees with the results from other codes  like qiskit or QuEST.  Could be a bug or could be there is something i do not doing right, in anyway i would appreciate any help. A minimal example to reproduce follows.
 
    #include <iostream>
    #include <cppsim/state.hpp>
    #include <cppsim/observable.hpp>
    #include<cppsim/gate_merge.hpp>
    #include<cppsim/gate_factory.hpp>
    #include <cppsim/circuit.hpp>
    #include <cppsim/utility.hpp>
    #include <vqcsim/parametric_circuit.hpp>

    int main(){
        QuantumState state(2);
        state.set_zero_state();

        QuantumCircuit QC(2);
        QC.add_RY_gate(0,-M_PI*0.1);
        QC.add_RY_gate(1,-M_PI*0.2);
        QC.add_CNOT_gate(1,0);
        QC.add_RY_gate(0,-M_PI*0.3);

        QC.update_quantum_state(&state);

        const CPPCTYPE* raw_data_cpp = state.data_cpp();

        for(size_t i=0;i<4;i++)
        {
                std::cout<<raw_data_cpp[i].imag()*raw_data_cpp[i].imag()+raw_data_cpp[i].real()*raw_data_cpp[i].real()<<std::endl;

        }
        return 0;
    }

The same code in qiskit 

    from qiskit import *
    import math

    backend = Aer.get_backend('statevector_simulator')
    vc=QuantumCircuit(2)
    vc.ry(math.pi*0.1,0)
    vc.ry(math.pi*0.2,1)
    vc.cnot(0,1)
    vc.ry(math.pi*0.3,0)

    job = backend.run(vc)
    result = job.result()
    outputstate = result.get_statevector(vc)
    for i, value in enumerate(outputstate.data):
        print((value.imag*value.imag+value.real*value.real))

**Comment by TysonRayJones** [comment]
Hi Eddy,

I believe this is likely the same issue as #291 .
Qulacs uses [convention](http://docs.qulacs.org/en/latest/guide/2.0_python_advanced.html#Quantum-gates)
```
Ry(theta) = exp(i Y theta/2)
```
whereas QuEST and Qiskit use convention
```
Ry(theta) = exp(- i Y theta/2)
```
If you add a minus to each of your Qulacs `add_RY_gate` parameters, the simulators will agree.
