### ISSUE TITLE
clang support

### ISSUE THREAD

**Issue by RodrigoAVargasHdz** [qulacs/qulacs#313]
Hi,

I understand from the documentation that Qulacs does not support `clang`, however, I was wondering if you have work on a version that is compatible with it. 
Do you have any tips on what types of changes are necessary to make it work with `clang`? 

Cheers,

**Comment by ikanago** [comment]
@RodrigoAVargasHdz we support building clang in #446.
Feel free to report any troubles to build with clang in another issue.
