### ISSUE TITLE
QuantumCircuitSimulator terminates abnormally.

### ISSUE THREAD

**Issue by forest1040** [qulacs/qulacs#344]
Even a code that does nothing as follows will terminate abnormally.

```
from qulacs import QuantumState, QuantumCircuit, QuantumCircuitSimulator, Observable
n = 3
state = QuantumState(n)

circuit = QuantumCircuit(n)
for i in range(n):
    circuit.add_H_gate(i)

sim = QuantumCircuitSimulator(circuit, state)
```

```
$ python sim.py
zsh: segmentation fault  python sim.py
```

**Comment by ikanago** [comment]
I reproduced the same error with C++ version, even without adding H gate.
```cpp
#include "cppsim/circuit.hpp"
#include "cppsim/observable.hpp"
#include "cppsim/simulator.hpp"
#include "cppsim/state.hpp"

int main() {
    const unsigned int n = 3;
    auto state = QuantumState(n);
    QuantumCircuit circuit(n);
    const auto simulator = QuantumCircuitSimulator(&circuit, &state);
}
```
Error emitted:
```
munmap_chunk(): invalid pointer
[1]    14717 abort      ./a.out
```
So this should be caused by the constructor of `QuantumCircuitSimulator`, not Python binding layer or others.

**Comment by ikanago** [comment]
Deleting following 3 `delete`s, the error disappeared.
https://github.com/qulacs/qulacs/blob/ddd6c8f38cbaf8c7a4bb72ced495d16e75117145/src/cppsim/simulator.cpp#L15-L19

This is because `delete`ing the pointer is not the responsibility of the class, but a scope which defined the pointee.

**Comment by forest1040** [comment]
https://github.com/qulacs/qulacs/pull/364
