### ISSUE TITLE
Fix deprecated warnings by GitHub Actions

### ISSUE THREAD

**Issue by Hiroya-W** [qulacs/qulacs#363]
Currently, GitHub Actions shows warnings.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, lukka/get-cmake, actions/setup-python, actions/cache, actions/cache, actions/setup-python, actions/checkout

To fix these, we need to update actions.

- actions/checkout@v3
- actions/setup-python@v4
- actions/cache@v3

But, **it appears that lukka/get-cmake does not yet support node16.**
https://github.com/lukka/get-cmake

We need to wait for an update or use another action.

**Comment by ikanago** [comment]
I stated the issue: [#46](https://github.com/lukka/get-cmake/issues/46)
