### ISSUE TITLE
Refactor cppsim_wrapper.cpp

### ISSUE THREAD

**Issue by KowerKoint** [qulacs/qulacs#382]
Pythonでの引数名がC++での引数名と一致していなくて統一されていなかったり、オーバーロードされている関数の1つを選ぶときにpy::overload_castを使ったり通常のキャスト演算子を使ったりでバラバラだったりするのを修正します。

**Comment by forest1040** [comment]
Python引数名の修正前はdeprecatedにして、しばらくおいておく感じですかね。。

**Comment by KowerKoint** [comment]
確かに、キーワード引数の書き方で書いてる人もいるかもしれないですね…
あからさまに間違ってるやつはさっさと直したいんですが…
