### ISSUE TITLE
qulacs.gate.Measurement behaves less randomly than expected

### ISSUE THREAD

**Issue by yutakahirano** [qulacs/qulacs#423]
Hi!

I'm using qulacs, and I found that qulacs.gate.Measurement behaves less randomly than I expected.

```python
import unittest
import clacs


class TestSimulation(unittest.TestCase):
    def test_hoge(self):
        m1 = qulacs.gate.Measurement(0, 0)
        m2 = qulacs.gate.Measurement(0, 0)
        for i in range(1000):
            s1 = qulacs.QuantumState(1)
            s2 = qulacs.QuantumState(1)
            qulacs.gate.H(0).update_quantum_state(s1)
            qulacs.gate.H(0).update_quantum_state(s2)
            m1.update_quantum_state(s1)
            m2.update_quantum_state(s2)
            self.assertEqual(s1.get_classical_value(0), s2.get_classical_value(0))
```

I expect this test to fail, but it actually passes on my environment.
I'm running this code on Ubuntu 20.04 on WSL2. Python version is 3.8.10, and qulacs version is 0.5.2.

**Comment by forest1040** [comment]
Thank you for contacting us.

After all, we have a 1/2 chance of returning 0 or 1, so
Here's how to count the number of matches:

```
import qulacs

def test_hoge():
    m1 = qulacs.gate.Measurement(0, 0)
    m2 = qulacs.gate.Measurement(0, 0)
    j = 0
    for i in range(1000):
        s1 = qulacs.QuantumState(1)
        s2 = qulacs.QuantumState(1)
        qulacs.gate.H(0).update_quantum_state(s1)
        qulacs.gate.H(0).update_quantum_state(s2)
        m1.update_quantum_state(s1)
        m2.update_quantum_state(s2)
        if s1.get_classical_value(0) != s2.get_classical_value(0):
            j = j + 1

        print(j)

test_hoge()

```

The result is 499, so I think it is correct, but what do you think?

**Comment by yutakahirano** [comment]
After investigating more, this seems more like a CPU problem. I'm using Ryzen 5 3600, and std::random_device returns a constant value on it. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100444 Each Measurement instance (or, QuantumGate_CPTP) [initializes its own random state with std::random_device](https://github.com/qulacs/qulacs/blob/main/src/cppsim/utility.hpp#L61), so it means all the measurement instances share the same seed.

I'm closing this issue as I think this is not a qulacs problem. Thank you!
