### ISSUE TITLE
split python test files

### ISSUE THREAD

**Issue by herring101** [qulacs/qulacs#424]
pythontestが一つのファイルに全部詰め込まれていて見にくいので、複数のファイルに分割したい。

**Comment by ikanago** [comment]
`python/test/` 以下に class ごとにファイルを分けてやるとよさそうですね．
複数ファイルに分割した場合は `python -m unittest discover` で一度に実行できるみたいです．
https://docs.python.org/3/library/unittest.html#test-discovery
