### ISSUE TITLE
Create a list of observables from existing one but with different coefficients

### ISSUE THREAD

**Issue by ikanago** [qulacs/qulacs#429]
## Prologue
[`QNNRegressor`](https://github.com/Qulacs-Osaka/scikit-qulacs/blob/74d656dfdd1339ee60d9f75aaa7a993d619a40e6/skqulacs/qnn/regressor.py#L18) in scikit-qulacs has a list of `Observable`s as a member variable. In [`QNNRegressor._cost_func_grad()`](https://github.com/Qulacs-Osaka/scikit-qulacs/blob/74d656dfdd1339ee60d9f75aaa7a993d619a40e6/skqulacs/qnn/regressor.py#L174) the class creates a list of observables from existing one for temporary use. The observables in the temporary list has a different coefficient from the original one.

## Problem
In [#254 in scikit-qulacs](https://github.com/Qulacs-Osaka/scikit-qulacs/pull/254), @Gruntrexpewrus posted code to construct `QNNRegressor` with arbitrary observables users supply. The problem is that the class have to hold string representations of an observable to create the temporary observable list in `QNNRegressor._cost_func_grad()` because we can construct `Observable` only from string.

So do we allow `QNNRegressor` have both observable list and observable string list, which may introduce some complexity?
If not, how do we deal with it? The most simple solution I come up with is implementing `Observable::set_coef(CPPCTYPE)`.

**Comment by forest1040** [comment]
I think, allow Observables to be string is freedom to measurement  expected value. (like a VQE)
But I don't understand why do we need it for QCL..
