### ISSUE TITLE
Failing CI in Windows when the chocolatey server is down

### ISSUE THREAD

**Issue by y-yu** [qulacs/qulacs#48]
- https://travis-ci.org/qulacs/qulacs/jobs/457537327#L70

### Methods to solve this issue

1. Ignore the result of Windows CI
    - We can use `allow_failures` to ignore the result of CI in Windows
        - See also: https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail
    - But it makes CI meaning to be unclear....
2. Implement retry and backoff logic to the chocolatey server in `.travis.yml`

**Comment by corryvrequan** [comment]
This is solved by PR #100 . Thanks for your contribution!
