### ISSUE TITLE
Remove deprecated commands in github Actions

### ISSUE THREAD

**Issue by kotamanegi** [qulacs/qulacs#489]
Actionsの中で現在Warningが出ているものは、以下の2つです。
- Node.js 12 が2023年の夏に使えなくなります。
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- GitHub Actionsのコマンドの一つである`save-state` と `set-output` が2023年6月1日から使えなくなります。
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

これらに対応するため、各種Actionsを改変します。

**Comment by ikanago** [comment]
Warning が出ているのは
- Jimver/cuda-toolkit
- markusjx/install-boost

で，cuda-toolkit は PR を出しました: https://github.com/Jimver/cuda-toolkit/pull/193
install-boost は2.4.3にあげればよさそうです．
