### ISSUE TITLE
Parameter not found in circuit when I create a parametrized CCCZ gate ?

### ISSUE THREAD

**Issue by camillerievan** [qulacs/qulacs#508]
I am trying to create a parametrized CCCZ gate.

If I use

`circuit.add_parametric_RZ_gate(3, -beta / math.pi)`

I can later call 

`circuit.set_parameter(4, beta0)`

The first 4 parameters are for another gate

However, to create the parametrized CCCZ gate I used the following:

```
    from qulacs.gate import to_matrix_gate
    rz_gate = qulacs_core.gate.ParametricRZ(3, -beta / math.pi)
    rz_matrix_gate = to_matrix_gate(rz_gate)
    rz_matrix_gate.add_control_qubit(2, 1)
    rz_matrix_gate.add_control_qubit(1, 1)
    rz_matrix_gate.add_control_qubit(0, 1)
    circuit.add_gate(rz_matrix_gate)
```

the problem is that I am later not finding the parameter and 

`circuit.set_parameter(4, beta0)`

returns 'parameter index is out of range'.  The first 4 parameters from the another gate are OK, but in this case I cannot find the fifth parameter!

What am I doing wrong?

**Comment by kwkbtr** [comment]
I guess when you do `to_matrix_gate()` the gate is converted to a non-parametric `DenseMatrix` gate, hence you can't update the parameter.
Unfortunately I don't have an idea about how to keep the gate parametric; I can only think of re-creating the gate every time you update the parameter.

**Comment by forest1040** [comment]
Currently, `QuantumGate_SingleParameter class` from which `ParametricRZ` inherits does not have `add_control_qubit()`, but we are considering adding it.
You might be able to use it when it's implemented.

**Comment by camillerievan** [comment]
Thanks for your replies.

**Comment by KowerKoint** [comment]
related to #510
