### ISSUE TITLE
[Bug] create_observable_from_openfermion_textが実部が０の時に失敗する

### ISSUE THREAD

**Issue by TenninYan** [qulacs/qulacs#51]
## 原因
恐らくパースする部分が (~~ + ~~j) [~ ~]という形を前提としていて、
0.25j [X0 Y1] みたいな実部が０である項の時に失敗する。

## 直すべきコード
多分この付近
https://github.com/qulacs/qulacs/blob/master/src/cppsim/observable.cpp#L109

## バグを生むコード
In [11]: jw_hamiltonian = jordan_wigner(FermionOperator(‘0^ 1’, 1))

In [12]: print(jw_hamiltonian)
(0.25+0j) [X0 X1] +
0.25j [X0 Y1] +
-0.25j [Y0 X1] +
(0.25+0j) [Y0 Y1]

In [13]: qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw_hamiltonian))
ValueError                                Traceback (most recent call last)
<ipython-input-13-5d343805fe2d> in <module>()
----> 1 qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw_hamiltonian))

ValueError: stod

**Comment by TenninYan** [comment]
あと0の時も失敗します。
とりあえず0の時は回避しますが直して頂ければm(_ _)m

## バグを生むコード

In [5]: jw = jordan_wigner(FermionOperator('0^ 0^ 0 0', 1))

In [6]: print(jw)
0

In [7]: qulacs_hamiltonian = create_observable_from_openfermion_text(str(jw))
[1]    3203 segmentation fault  ipython

**Comment by corryvrequan** [comment]
This is fixed in PR #73.
