### ISSUE TITLE
Wrong type annotation for numpy.ndarray

### ISSUE THREAD

**Issue by kwkbtr** [qulacs/qulacs#537]
One example is here:
https://github.com/qulacs/qulacs/blob/5c654d21037e8ce82db0a69a398d486044a4fcbc/pysrc/qulacs/__init__.pyi#L999

The first type variable of `numpy.ndarray` is `_ShapeType`, whereas the first one in the above example is `numpy.complex128`.
https://github.com/numpy/numpy/blob/8cec82012694571156e8d7696307c848a7603b4e/numpy/__init__.pyi#L1482

**Comment by KowerKoint** [comment]
I see, and it's the problem of mypy-stubgen.
https://github.com/sizmailov/pybind11-stubgen/blob/master/pybind11_stubgen/__init__.py#L249
In https://github.com/sizmailov/pybind11-stubgen/issues/34 , the parameters are only for users (not mypy). However, mypy actually uses this information.

Only way for me to deal with this is to make a script to overwrite ndarray signatures by simple regex replacement.

**Comment by KowerKoint** [comment]
I'm thinking of making all stubs of qulacs manually.

**Comment by kwkbtr** [comment]
Thank you for the information.
From the pybind11-stubgen issue you mentioned, I found another issue https://github.com/sizmailov/pybind11-stubgen/issues/41 that [adds `--bare-numpy-ndarray` option](https://github.com/sizmailov/pybind11-stubgen/commit/54335c1af4c1a0f9cee76156ec494151ca732c53).
Maybe it is worth trying it.

> I'm thinking of making all stubs of qulacs manually.

It sounds good if possible and manageable :)

**Comment by KowerKoint** [comment]
Thank you.
I added `--bare-numpy-ndarray` in #542 .
I'm still considering to managing them manually in the future...
