### ISSUE TITLE
Implement a new method in QuantumCircuit/ParametricQuantumCircuit that returns instance of index'th QuantumGate

### ISSUE THREAD

**Issue by kosukemtr** [qulacs/qulacs#54]

**Comment by corryvrequan** [comment]
This function is implemented in #55 with some bug fixes. Thanks for nice feature issue!

p.s.
If you have some typical code snippets for parametric gate function, please add your codes to 
./python/test/test_qulacs.py as a test function. It is very helpful for us to check backward compatibility in updates.
