### ISSUE TITLE
Support for the latest GCC version?

### ISSUE THREAD

**Issue by ekapit** [qulacs/qulacs#599]
Hi,

I've been using qulacs extensively since the summer, and the performance is great for the CPU version. However when I try to build it against the GPU it fails because it demands to use an older version of GCC (version 8) and my linux machines all have version 9 (the default installed with ubuntu 20.04). I was able to get it to CPU compile for each machine by tinkering with the scripts (to call GCC8 specifically instead of GCC) but wasn't able to get that to work for the CUDA version. Can you update the package accordingly so it will compile with newer GCC versions? 

Thanks,
Eliot

**Comment by forest1040** [comment]
Thank you.

For development, I use a docker container, but you can build with the new gcc.
https://github.com/qulacs/qulacs/blob/main/.devcontainer/gpu/Dockerfile
for more information.
