### ISSUE TITLE
Typos in CONTRIBUTING.md ?

### ISSUE THREAD

**Issue by shim98a** [qulacs/qulacs#602]
Hi! I would like to report two things about the contents of `CONTRIBUTING.md`.

1. In the line 68, maybe "vertualenv" should be "virtualenv"?
https://github.com/qulacs/qulacs/blob/ed458a4d97c754cb6df00e4e83f381d147e3d20c/CONTRIBUTING.md?plain=1#L68

2. The line 28 says PRs need to be created to the `dev` branch. But I couldn't find the `dev` branch in the current branch list. Does this repository still have a development branch?  To which branch do PRs have to be created?
https://github.com/qulacs/qulacs/blob/ed458a4d97c754cb6df00e4e83f381d147e3d20c/CONTRIBUTING.md?plain=1#L28

Thank you!

**Comment by KowerKoint** [comment]
1. fixing in #609
2. Sorry, we changed the default branch from `dev` to `main` before. I'll fix it.
