### ISSUE TITLE
[Bug/python] add_gate() in ParametricQuantumCircuit fails when called as add_gate(gate, position)

### ISSUE THREAD

**Issue by kosukemtr** [qulacs/qulacs#63]
I find the cause is the line 257 and 258 of cppsim_wrapper.cpp. They are the same.

https://github.com/qulacs/qulacs/blob/d808cedf634e164ade54b02395d58f71bfcb10e5/python/cppsim_wrapper.cpp#L257

**Comment by corryvrequan** [comment]
PR is approved. Thanks!
