### ISSUE TITLE
`python3.12` installation

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qulacs/qulacs#645]
Hello, installing the cpu version of `qulacs` under `python3.12` simply with `pip install qulacs` fails for me. Separately installing `cmake` and `boost` first, solves the problem though.

**Comment by ikanago** [comment]
Thank you for reporting the issue!
I have confirmed that `pip install qulacs` needs cmake and boost on Python 3.12.
We have introduced the setting to build for Python 3.12 on #620, but we haven't released a new version after that.
We are going to publish a new version including the build for Python 3.12 before long.

**Comment by scarrazza** [comment]
@ikanago thank you for the information. As soon as you release the new version we will be able to merge https://github.com/qiboteam/qibo/pull/1272 and release a new Qibo version including the qulacs backend.

**Comment by ikanago** [comment]
@scarrazza Now qulacs 0.6.4.1 is available. This version is compatible for Python 3.12.
If you have further problems, feel free to inform at this or other issue!

**Comment by BrunoLiegiBastonLiegi** [comment]
Thanks @ikanago, `python 3.12` works like charm now! However, we are having problems with `python 3.9` under `macos`. The reason seems to be that no wheel is available for the ARM version of `macos` with `3.9`, although it's there for all the other python versions. Is there by chance any plan for adding it?

**Comment by forest1040** [comment]
ok! i recheck it. for macos.

**Comment by KowerKoint** [comment]
Python < 3.10 for setup-python was not supported in macos arm64 runner, so we excluded 3.8 and 3.9 in https://github.com/qulacs/qulacs/pull/631 .
Now it seems supported. I'll try to support it.
