### ISSUE TITLE
Pauli observable matrix not expected

### ISSUE THREAD

**Issue by philwang66** [qulacs/qulacs#651]
I was trying to calculate the expectation value of Pauli Z over some state

observable = Observable(2)
observable.add_operator(1.0, "Z 1")
obs = observable.get_matrix()
print(obs.todense())

I get
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]]

while for "Z 0" it is
[[ 1.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -1.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  1.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j -1.+0.j]]

Should it be opposite according to definition of Kronecker Product?

**Comment by KowerKoint** [comment]
In qulacs, larger index is placed outer. This is opposite to the general definition, but it is sometimes useful when you're thinking of binary representation.

$\ket{2}=\ket{10_{(2)}}=(0, 0, 1, 0)^{T}$, where second (0-indexed) place of amplitudes has 1.
