### ISSUE TITLE
`merge` not working for CPTP

### ISSUE THREAD

**Issue by NnktYoshioka** [qulacs/qulacs#668]
`merge` function is not properly working for CPTP maps (tested only for v0.6.5)

More specifically, I wanted to create a PauliMeasurement Instrument while I can currently do this only by directly implementing them in `QuantumCircuit`, as shown in the following code.

```python
import numpy as np
from qulacs.gate import merge, H, S, Sdag, CNOT, Measurement
from qulacs import QuantumCircuit, QuantumState

def add_PauliMeasurement(circuit, pauli_id_list, qubit_pos_list, register):
    qubit1 = qubit_pos_list[0]
    for k in range(len(pauli_id_list)):
        pauli_id = pauli_id_list[k]
        qubit_pos = qubit_pos_list[k]

        if pauli_id == 1:
            circuit.add_H_gate(qubit_pos)
        elif pauli_id == 2:
            circuit.add_Sdag_gate(qubit_pos)
            circuit.add_H_gate(qubit_pos)

        if k > 0:
            circuit.add_CNOT_gate(qubit_pos, qubit1)

    circuit.add_gate(Measurement(qubit1, register))

    for k in range(len(pauli_id_list)):
        pauli_id = pauli_id_list[k]
        qubit_pos = qubit_pos_list[k]
        
        if k > 0:
            circuit.add_CNOT_gate(qubit_pos, qubit1)            

        if pauli_id == 1:
            circuit.add_H_gate(qubit_pos)
        elif pauli_id == 2:
            circuit.add_H_gate(qubit_pos)
            circuit.add_S_gate(qubit_pos)

def PauliMeasurement(pauli_id_list, qubit_pos_list, register):
    gate_list = []
    gate_list_dag = []

    for k in range(len(pauli_id_list)):
        pauli_id = pauli_id_list[k]
        qubit_pos = qubit_pos_list[k]

        if pauli_id == 1:
            gate_list.append(H(qubit_pos))
        elif pauli_id == 2:
            gate_list.append(Sdag(qubit_pos))
            gate_list.append(H(qubit_pos))

        if k > 0:
            gate_list.append(CNOT(qubit_pos, qubit1))

        if k > 0:
            gate_list_dag.append(CNOT(qubit_pos, qubit1))
        if pauli_id == 1:
            gate_list_dag.append(H(qubit_pos))
        elif pauli_id == 2:
            gate_list_dag.append(H(qubit_pos))
            gate_list_dag.append(S(qubit_pos))
    g = merge(gate_list + [Measurement(qubit_pos_list[0], register)] + gate_list_dag)

    return g


pauli_id_list_1q = [3]
qubit_pos_list_1q = [0]

g = PauliMeasurement(pauli_id_list_1q, qubit_pos_list_1q, register = 0)
qc = QuantumCircuit(1)
add_PauliMeasurement(qc, pauli_id_list_1q, qubit_pos_list_1q, register = 1)

# merged gate based
state1 = QuantumState(1)
state1.load(np.array([1, -1,])/np.sqrt(2))
g.update_quantum_state(state1)
print(state1.get_vector()) # not working properly

# circuit-based
state2 = QuantumState(1)
state2.load(np.array([1, -1,])/np.sqrt(2))

qc.update_quantum_state(state2)
print(state2.get_vector()) # this is fine
```

Of course I can use the `Instrument` function by specifying the Kraus operators, while I am currently not aware how to easily create `QuantumGateBase` object corresponding to (Identity +- Pauli)/2 for multiqubit Pauli operators.

Any help is greatly welcome, thanks in advance!

**Comment by KowerKoint** [comment]
`merge` generates a new `DenseMatrix` gate by converting each gate into a matrix and combining them. Since CPTP-maps cannot be represented by a single matrix, this functionality is not supported. (You may have noticed the runtime warning: `* Warning : Gate-matrix of CPTP-map cannot be obtained. Identity matrix is returned.`)

In general, it is recommended to construct quantum circuits that perform measurements in the computational basis, as shown in `add_PauliMeasurement`.

If you must combine it into a single gate, you can implement it as follows to generate an `Instrument` consisting of `DenseMatrix` gates:

```python
from qulacs.gate import DenseMatrix, Instrument, Pauli
def PauliMeasurement(pauli_id_list, qubit_pos_list, register):
    pauli = Pauli(qubit_pos_list, pauli_id_list)
    pauli_mat = pauli.get_matrix()
    identity_mat = np.eye(1 << len(qubit_pos_list))

    measure0 = DenseMatrix(qubit_pos_list, (pauli_mat + identity_mat) / 2)
    measure1 = DenseMatrix(qubit_pos_list, (pauli_mat - identity_mat) / 2)

    return Instrument([measure0, measure1], register)
```

However, this method explicitly creates a $2^n \times 2^n$ matrix, so it may take significant computation time when $n$ is large.

If you believe having a single gate to perform Kraus measurements with general Pauli operators would be useful, please let us know, and we can consider adding such functionality.

**Comment by NnktYoshioka** [comment]
Hi thank you for the reply. I personally think that many people (or myself) wish to debug Clifford simulations using full state simuators like qulacs, or sometimes even use for actual research when Clifford simulation is not valid (e.g. magic state distillation). Multiqubit measurements allow more simpler implementation of stabilizer measurements for numerics of error correction, which would be of great interest for quantum computing researchers :)

**Comment by KowerKoint** [comment]
Thank you for your reply.
I'm thinking of implementing it on #670 .
