### ISSUE TITLE
[Question] How can I unlock multi-threading in C++ multi-core?

### ISSUE THREAD

**Issue by BMalaca** [qulacs/qulacs#669]
Dear Qulacs team,

I built the static libraries with MPI and SVE support. I got jobs to successfully run up to 38 qubits in 256 Fujitsu's A64FX nodes. However, it seems that they are only using one core in each node, even though I run the recommended commands for OpenMP usage:

export OMP_NUM_THREADS=48
export QULACS_NUM_THREADS=48

I'm also on slack if you prefer a more immediate response.

**Comment by mkrompiec** [comment]
hi, can you share how you solved this issue?
