### ISSUE TITLE
[Bug] The parameter count in ParametricQuantumCircuit does not behave correctly when adding parametric gate by add_gate(ParametricGate)

### ISSUE THREAD

**Issue by kosukemtr** [qulacs/qulacs#69]
Not in hurry.
But is it so that a parametric gate has to be added using for example add_parametric_RY_gate(target, angle)?

**Comment by corryvrequan** [comment]
This is not a bug.
There is a function ParametricQuantumCircuit::add_parametric_gate to add a new gate instance as a parametric gate. 
If a parametric gate is added through ParametricQuantumCircuit::add_gate, the angle of the gate is not managed as a tunable parameter.

**Comment by corryvrequan** [comment]
This is not documented because these parametric features are exported recently.
Since simulation of VQE may be a popular use of this library, I believe tutorials about parametric circuits must be added as soon as possible.
