### ISSUE TITLE
Export ParametricGate class to python

### ISSUE THREAD

**Issue by kosukemtr** [qulacs/qulacs#72]
Not in hurry.
add_parametric_gate() method in ParametricQuantumCircuit class cannot be used from python because its argument has to be ParametricGate and it has not been exported. Even when getting an instance of ParametricGate via ParametricQuantumCircuit.get_gate() function, python sees it as an instance of QuantumGateBase.

**Comment by corryvrequan** [comment]
Though I forget when it was, I think this issue is resolved in previous PRs. 
If not, please reopen it.
